# Generated by Django 5.2.11 on 2026-02-06 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_company', models.CharField(blank=True, max_length=255)),
                ('preferred_role', models.CharField(blank=True, max_length=255)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('interest_fields', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('INFER', 'Infer')], max_length=5)),
                ('ai_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Event',
                'verbose_name_plural': 'Onboarding Events',
            },
        ),
    ]
