# Generated by Django 5.2.11 on 2026-02-06 13:35

from django.db import migrations, models


def copy_user_text(apps, schema_editor):
    OnboardingEvent = apps.get_model('api', 'OnboardingEvent')
    for event in OnboardingEvent.objects.all():
        event.user_input = getattr(event, 'interest_fields', '') or ''
        event.final_company = ''
        event.final_role = ''
        if event.ai_response is None:
            event.ai_response = ''
        event.save(update_fields=['user_input', 'final_company', 'final_role', 'ai_response'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingevent',
            name='user_input',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='onboardingevent',
            name='final_company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='onboardingevent',
            name='final_role',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='onboardingevent',
            name='ai_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(copy_user_text, noop_reverse),
        migrations.RemoveField(
            model_name='onboardingevent',
            name='preferred_company',
        ),
        migrations.RemoveField(
            model_name='onboardingevent',
            name='preferred_role',
        ),
        migrations.RemoveField(
            model_name='onboardingevent',
            name='major',
        ),
        migrations.RemoveField(
            model_name='onboardingevent',
            name='interest_fields',
        ),
        migrations.RemoveField(
            model_name='onboardingevent',
            name='status',
        ),
    ]
