# Generated by Django 5.2.11 on 2026-02-07 00:00

from django.db import migrations, models


def seed_empty_history(apps, schema_editor):
    OnboardingEvent = apps.get_model('api', 'OnboardingEvent')
    for event in OnboardingEvent.objects.all():
        if event.history is None:
            event.history = []
            event.save(update_fields=['history'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_simplify_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingevent',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='OnboardingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=models.CASCADE, related_name='messages', to='api.onboardingevent')),
            ],
            options={'ordering': ['created_at']},
        ),
        migrations.RunPython(seed_empty_history, noop_reverse),
    ]
