# Generated by Django 5.2.11 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_conversation_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingevent",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
