# Generated by Django 5.2.11 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_add_summary_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingevent",
            name="score_one_result",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingevent",
            name="score_two_result",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingevent",
            name="roadmap_result",
            field=models.TextField(blank=True, default=""),
        ),
    ]
