# Generated by Django 5.2.11 on 2026-02-07 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_add_score_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoadmapPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField()),
                ("raw_text", models.TextField()),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("total_months", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="roadmap_plans", to="api.onboardingevent"),
                ),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("event", "version")}},
        ),
        migrations.CreateModel(
            name="RoadmapItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("priority", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("duration_weeks", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("importance_score", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("category", models.CharField(blank=True, default="", max_length=255)),
                ("detail_text", models.TextField(blank=True, default="")),
                (
                    "plan",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="api.roadmapplan"),
                ),
            ],
            options={"ordering": ["priority", "id"]},
        ),
        migrations.CreateModel(
            name="RoadmapProgressEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("blocked", "Blocked"),
                            ("done", "Done"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("percent_complete", models.PositiveIntegerField(default=0)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="progress_entries", to="api.roadmapitem"),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="RoadmapJournalEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_note", models.TextField()),
                ("ai_evaluation", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="journal_entries", to="api.roadmapitem"),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
