# Generated by Django 5.2.11 on 2026-02-07 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_roadmap_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        choices=[("jobkorea", "JobKorea"), ("data_portal", "DataPortal")], max_length=50
                    ),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField(max_length=500)),
                ("summary", models.TextField(blank=True, default="")),
                ("category", models.CharField(blank=True, default="", max_length=255)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"unique_together": {("source", "source_id", "link")}},
        ),
        migrations.CreateModel(
            name="OpportunityMatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("dismissed", "Dismissed"),
                            ("injected", "Injected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ai_feedback", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_matches",
                        to="api.onboardingevent",
                    ),
                ),
                (
                    "inserted_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_sources",
                        to="api.roadmapitem",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="api.opportunity",
                    ),
                ),
            ],
            options={"ordering": ["-score", "-created_at"], "unique_together": {("event", "opportunity")}},
        ),
    ]
