# Generated by Django 5.2.11 on 2026-02-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_opportunity_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("jobkorea_keywords", models.JSONField(blank=True, default=list)),
                ("dataportal_keywords", models.JSONField(blank=True, default=list)),
                ("max_items_per_source", models.PositiveIntegerField(default=5)),
                ("recent_days", models.PositiveIntegerField(default=14)),
                ("min_score", models.FloatField(default=40.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Opportunity Configuration",
                "verbose_name_plural": "Opportunity Configurations",
            },
        ),
    ]
