# Generated by Django 5.2.11 on 2026-02-07 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_opportunity_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmapitem",
            name="is_recommendation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roadmapitem",
            name="origin_opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roadmap_items",
                to="api.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="roadmapitem",
            name="recommendation_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
