# Generated by Django 5.2.11 on 2026-02-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_roadmapitem_recommendations"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunitymatch",
            name="priority_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
