# Generated by Django 5.2.11 on 2026-02-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_opportunitymatch_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunitymatch',
            options={'ordering': ['-priority_score', '-score', '-created_at']},
        ),
    ]
